### ISSUE TITLE
Do you have plans to Windows release

### ISSUE THREAD

**Issue by DaniloJacques** [todxx/tdxminer#1]
There is a big lack of Lyra2z miners for Windows. Your hash predictions is impressive.

Do you have plans about release for Windows?

**Comment by todxx** [comment]
Good news on the windows/amdgpu-pro front.  I should have a version that works with amdgpu-pro drivers in about a day or two.  I think I can get a windows version together within a week or two.

**Comment by todxx** [comment]
Bad news on the windows front.  Some things have come up and I am unable to make much progress on porting to windows.  I'm not sure when I will be able to get the windows version working, so I suggest trying to use the linux version.
