### ISSUE TITLE
Crashes speed to zero on cards

### ISSUE THREAD

**Issue by Legat88** [todxx/tdxminer#3]
Hello, I have 4 GPU RX580 and after run your miner first GPU have full speed, but others become slower down to zero. Screenshot here: [https://imgur.com/a/pDXKe](url)
OS - HiveOS

**Comment by todxx** [comment]
I have not encountered this problem before, so I'm not sure what might be causing it.  It is possible that the GPUs have crashed if they are overclocked.  Does restarting the miner get the GPUs to function again?

**Comment by cdarken** [comment]
Most probably the GPUs have either too much overclock or too much undervolt, that's what I experienced myself.

**Comment by Legat88** [comment]
I solved this problem by setting higher undervolt from 950 mV to 1000 mV.
